### ISSUE TITLE
Can't install `py2neo`

### ISSUE THREAD

**Issue by ShutdownRepo** [kaluche/bloodhound-quickwin#2]
Can't install the `py2neo` requirement. While it's not bloodhound-quickwin's problem per se, while `py2neo` can't be installed, bhqc can't be used. Is there any alternative to `py2neo` here?
```
$ pip3 install py2neo
ERROR: Could not find a version that satisfies the requirement py2neo (from versions: none)
ERROR: No matching distribution found for py2neo
```

**Comment by kaluche** [comment]
Hey Charlie, and thanks.
Proabably linked to https://community.neo4j.com/t/farewell-py2neo-what-happens-now/64419 ...I will take a look at the Neo4j Python Driver to determine if the migration is the best solution.

**Comment by ShutdownRepo** [comment]
Ah! Interesting, didn't see that
Maybe manually compiling & installing a fork in the mean time is the best short-term solution 🤷‍♂️

**Comment by ShutdownRepo** [comment]
Temporary fix.
Either manually:
```bash
git clone https://github.com/kaluche/bloodhound-quickwin
cd bloodhound-quickwin
python3 -m venv ./venv/
source ./venv/bin/activate
pip3 install git+https://github.com/elena/py2neo
pip3 install -r requirements.txt
```
Or with PR #3
