### ISSUE TITLE
"Can configure Resource-Based Constrained Delegation" missing privileges

### ISSUE THREAD

**Issue by Signum21** [kaluche/bloodhound-quickwin#4]
There are other privileges that let you configure a Resource-Based Constrained Delegation:

GenericAll
GenericWrite
Owns
WriteAccountRestrictions
WriteDacl
WriteOwner
AllExtendedRights

Source: https://github.com/BloodHoundAD/BloodHound/tree/master/src/components/Modals/HelpTexts

**Comment by kaluche** [comment]
You're totally right. This should be fixed now in https://github.com/kaluche/bloodhound-quickwin/commit/390046e3f3d5a9bb1bb1a3df3740e73f58235286.
